name: Debian Package for ARM
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [linux, ARM]
    container:
      image: ubuntu:latest
    steps:
    - name: Update packet sources
      run:  apt update -y
    - name: Install dependencies
      run:  apt install -y devscripts build-essential lintian debhelper libudev-dev
    - uses: actions/checkout@v2
    - name: Build debian package
      run: |
        dpkg-buildpackage -us -uc
        mkdir package/
        mv ../unipager_*.deb package/
    - name: Push to cloudsmith.io
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'deb'
        owner: 'rwth-afu'
        repo: 'unipager'
        distro: 'raspbian'
        release: 'buster'
        republish: 'true'
        file: './package/*.deb'
